language: python
sudo: required
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install mosquitto
install:
  - make travis-deps
  - python setup.py install
# command to run tests
script:
 #- make tests
 - nosetests --verbosity=2 --cover-package=janitoo,janitoo_db,janitoo_manager --cover-min-percentage= --with-coverage --cover-inclusive --cover-tests --cover-html --cover-html-dir=build/docs/html/tools/coverage --with-html --html-file=build/docs/html/tools/nosetests/index.html tests/test_flask
 - nosetests --verbosity=2 --cover-package=janitoo,janitoo_db,janitoo_manager --cover-min-percentage= --with-coverage --cover-inclusive --cover-tests --cover-html --cover-html-dir=build/docs/html/tools/coverage --with-html --html-file=build/docs/html/tools/nosetests/index.html tests/test_socketio
