"""empty message

Revision ID: 3377fadf330d
Revises: 105d9bf06d3a
Create Date: 2015-11-07 02:34:41.510449

"""

# revision identifiers, used by Alembic.
revision = '3377fadf330d'
down_revision = '105d9bf06d3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
